# DE: Bundle-Routes f√ºr Showcase-Controller
# EN: Bundle routes for showcase controller
#
# In der Host-App einbinden via config/routes/tabler.yaml:
#
#   tabler_bundle:
#       resource: '@TablerBundle/config/routes.yaml'
#       prefix: /tabler

tabler_showcase:
    resource: '../src/Controller/'
    type: attribute
