services:
    _defaults:
        autowire: true
        autoconfigure: true

    # DE: FormTypes f√ºr Tabler Design System
    # EN: FormTypes for Tabler Design System
    Jostkleigrewe\TablerBundle\Form\Type\:
        resource: '../src/Form/Type/'
        tags: ['form.type']
